### ISSUE TITLE
Response statut

### ISSUE THREAD

**Issue by romain-malet** [sgadois/ProjetIAWSRest#13]
Try this : http://www.omdbapi.com/?i=56&r=xml 
And look at the response statut. 
To see it you can use Firebug or Web developper extensions for Firefox.
Or use developper tools for Chrome.

**Comment by abakarEgrey** [comment]
When I try http://www.omdbapi.com/?i=56&r=xml on Google chrome, I have this response:
Server Error in '/' Application.

A potentially dangerous Request.Path value was detected from the client (&).

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Web.HttpException: A potentially dangerous Request.Path value was detected from the client (&).

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[HttpException (0x80004005): A potentially dangerous Request.Path value was detected from the client (&).]
   System.Web.HttpRequest.ValidateInputIfRequiredByConfig() +12391095
   System.Web.PipelineStepManager.ValidateHelper(HttpContext context) +166

**Comment by romain-malet** [comment]
With Chrome, be careful with its cache, you can have a 304 not modified.
