### ISSUE TITLE
Accessing resources

### ISSUE THREAD

**Issue by romain-malet** [sgadois/ProjetIAWSRest#16]
What do you think of putting the resource "associate" either in films or in theater ?
Currently, accessing resource by 
http://.../associate/{filmId}/{theaterId}
If we put it in films
http://.../films/{filmId}/theaters/{theaterId}
Or in theaters
http://.../theaters/{theaterId}/films/{filmId}

If we chose to change the access, I prefer put it into theater resource because we have an already access to find theater whose have film : http://.../theaters/films/{filmId}

It's a question.

**Comment by abakarEgrey** [comment]
Je suis d'accords qu'on mette la ressource associate dans theater.

Envoyé de mon iPhone

**Comment by romain-malet** [comment]
En y réfléchissant, je le mettrai dans films et je mettrai aussi la recherche de salle par imdbID (on en avait parlé de ça je crois) en remplacant la recherche de film par une query. Ce qui nous donnerait : 
dans films
E1 - GET http://example.com/films?titre=blabla(&year=1871)
E4 - GET http://example.com/films/tt0012345/theaters
E3 - PUT http://example.com/films/tt0012345/theaters/42
dans theaters
E2 - GET http://example.com/theaters?dep=31...

Ca serait pas plus cohérent et intuitif comme accès ?

**Comment by romain-malet** [comment]
Au temps pour moi, je pense m'être trompé en définissant la méthode PUT pour l'E3 (même s'il y aurait une justification à le faire).
Il faudrait donc définir l'accès au POST.
Je propose : http://example.com/films/theaters
De plus dans le retour du post on pourrait mettre un lien : 
http://example.com/films/ID_du_film_qu'on_vient_associer/theaters

Qu'en pensez-vous ?

**Comment by romain-malet** [comment]
S'il on considère l'ajout d'un film dans une salle (E3) comme une mise à jour de la salle, ne vaudrait-il pas mieux y accéder par : 
PUT http://example.com/theaters/42

EDIT: Pas du tout... On doit associé UN film à une ou plusieurs salles, donc : 
http://example.com/films/tt0012345

les acces : 
GET http://example.com/films?titre=blabla[&year=1871]
GET http://example.com/films/tt0012345/theaters
PUT http://example.com/films/tt0012345
GET http://example.com/theaters?dep=31...

**Comment by romain-malet** [comment]
Au temps pour moi, en relisant les spec w3c, c'est plutôt POST pas un PUT
POST Extending a database through an append operation
