### ISSUE TITLE
Utilisation de apache common

### ISSUE THREAD

**Issue by romain-malet** [sgadois/ProjetIAWSRest#2]
Il est inutile d'utilisé l'api d'apache pour dev un client car jersey le propose.
Inutile donc d'ajouter la dépendance.
J'ai push sur le master un exemple dans MyResource.
Je te propose de plutôt repartir la dessus.

De plus, le client jersey nous servira pour les tests !

EDIT: MyResource est devenu FilmResource

**Comment by abakarEgrey** [comment]
ok. Je repartirai sur le nouveau code
